name = "lager"
compatibility_date = "2026-02-12"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "lager-db"
database_id = "0a8d0000-a44c-477d-bdfb-c1c12a8767d5"
preview_database_id = "DB"

